.TH "GCLOUD ALPHA BIGQUERY JOBS SHOW-ROWS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_bigquery_jobs_show-rows \- displays selected rows in the result of a query job
.SH "SYNOPSIS"
.sp
gcloud alpha bigquery jobs show\-rows \fIJOB_ID\fR [\fB\-\-fingerprint\-job\-id\fR] [\fB\-\-limit\fR \fILIMIT\fR; default="100"] [\fB\-\-start\-row\fR \fISTART_ROW\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Displays selected rows in the result of a query job\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIJOB_ID\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-limit\fR \fILIMIT\fR; default="100"
.RS 4
The maximum number of rows to display\&.
.RE
.PP
\fB\-\-start\-row\fR \fISTART_ROW\fR
.RS 4
The number of rows to skip before showing table data\&.
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-fingerprint\-job\-id\fR
.RS 4
Whether to use a job id that is derived from a fingerprint of the job configuration\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBbigquery\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
