.TH "GCLOUD COMPUTE HTTP-HEALTH-CHECKS LIST" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_http-health-checks_list \- list Google Compute Engine health checks
.SH "SYNOPSIS"
.sp
gcloud compute http\-health\-checks list [\fINAME\fR \&...] [\fB\-\-limit\fR \fILIMIT\fR] [\fB\-\-regexp\fR \fIREGEXP\fR, \fB\-r\fR \fIREGEXP\fR] [\fB\-\-sort\-by\fR \fISORT_BY\fR] [\fB\-\-uri\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute http\-health\-checks list\fR displays all Google Compute Engine health checks in a project\&.
.SH "POSITIONAL ARGUMENTS"
.HP
[\fINAME\fR \&...]
.RE
.SH "FLAGS"
.PP
\fB\-\-limit\fR \fILIMIT\fR
.RS 4
The maximum number of results\&.
.RE
.PP
\fB\-\-regexp\fR \fIREGEXP\fR, \fB\-r\fR \fIREGEXP\fR
.RS 4
A regular expression to filter the names of the results on\&. Any names that do not match the entire regular expression will be filtered out\&.
.RE
.PP
\fB\-\-sort\-by\fR \fISORT_BY\fR
.RS 4
A field to sort by\&. To perform a descending\-order sort, prefix the value of this flag with a tilde (\fI~\fR)\&.
.RE
.PP
\fB\-\-uri\fR
.RS 4
If provided, the list command will only print URIs for the resources returned\&. If this flag is not provided, the list command will print a human\-readable table of useful resource data\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To list all health checks in a project in table form, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute http\-health\-checks list
.fi
.if n \{\
.RE
.\}
.sp
To list the URIs of all health checks in a project, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute http\-health\-checks list \-\-uri
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
