.TH "GCLOUD COMPUTE TARGET-HTTP-PROXIES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_target-http-proxies \- list, create, and delete target HTTP proxies
.SH "SYNOPSIS"
.sp
gcloud compute target\-http\-proxies \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
List, create, and delete target HTTP proxies\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBcreate\fR
.RE
.PP
\fBdelete\fR
.RS 4
Delete target HTTP proxies\&.
.RE
.PP
\fBdescribe\fR
.RS 4
Display detailed information about a target HTTP proxy\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine target HTTP proxies\&.
.RE
.PP
\fBupdate\fR
.RS 4
Update a target HTTP proxy\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
