.TH "GCLOUD COMPUTE HTTP-HEALTH-CHECKS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_http-health-checks \- read and manipulate HTTP health checks for load balanced instances
.SH "SYNOPSIS"
.sp
gcloud compute http\-health\-checks \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Read and manipulate HTTP health checks for load balanced instances\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBcreate\fR
.RE
.PP
\fBdelete\fR
.RS 4
Delete HTTP health checks\&.
.RE
.PP
\fBdescribe\fR
.RS 4
Display detailed information about an HTTP health check\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine health checks\&.
.RE
.PP
\fBupdate\fR
.RS 4
Update an HTTP health check\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
