.TH "GCLOUD SQL INSTANCES PROMOTE-REPLICA" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_sql_instances_promote-replica \- promotes Cloud SQL read replica to a stand\-alone instance
.SH "SYNOPSIS"
.sp
gcloud sql instances promote\-replica \fIREPLICA\fR [\fB\-\-async\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Promotes Cloud SQL read replica to a stand\-alone instance\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIREPLICA\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-async\fR
.RS 4
Do not wait for the operation to complete\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBsql\fR component\&. See installing components if it is not installed\&.
