.TH "GCLOUD ALPHA DATAFLOW JOBS LIST" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_dataflow_jobs_list \- lists all jobs in a particular project
.SH "SYNOPSIS"
.sp
gcloud alpha dataflow jobs list [\fIJOB\fR \&...] [\fB\-\-created\-after\fR \fICREATED_AFTER\fR] [\fB\-\-created\-before\fR \fICREATED_BEFORE\fR] [\fB\-\-job\-name\fR \fIJOB_NAME\fR] [\fB\-\-status\fR \fISTATUS\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR By default, jobs in the current project are listed; this can be overridden with the gcloud \-\-project flag\&.
.SH "POSITIONAL ARGUMENTS"
.HP
[\fIJOB\fR \&...]
.RE
.SH "FLAGS"
.PP
\fB\-\-created\-after\fR \fICREATED_AFTER\fR
.RS 4
Filter the jobs to those created after the given time
.RE
.PP
\fB\-\-created\-before\fR \fICREATED_BEFORE\fR
.RS 4
Filter the jobs to those created before the given time
.RE
.PP
\fB\-\-job\-name\fR \fIJOB_NAME\fR
.RS 4
Filter the jobs to those with the given name\&.
.RE
.PP
\fB\-\-status\fR \fISTATUS\fR
.RS 4
Filter the jobs to those with the selected status
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
