.TH "GCLOUD BETA CONTAINER CLUSTERS DESCRIBE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_beta_container_clusters_describe \- describe an existing cluster for running containers
.SH "SYNOPSIS"
.sp
gcloud beta container clusters describe \fINAME\fR [\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(BETA)\fR Describe an existing cluster for running containers\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fINAME\fR
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 4
The compute zone (e\&.g\&. us\-central1\-a) for the cluster
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in BETA and may change without notice\&.
