.TH "GCLOUD ALPHA DATAFLOW JOBS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_dataflow_jobs \- a group of subcommands for working with Dataflow jobs
.SH "SYNOPSIS"
.sp
gcloud alpha dataflow jobs \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR A group of subcommands for working with Dataflow jobs\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBcancel\fR
Cancels all jobs that match the command line arguments\&.
.RE
.PP
\fBdescribe\fR
.RS 4
\fB(ALPHA)\fR
Outputs the Job object resulting from the Get API\&.
.RE
.PP
\fBexport\-steps\fR
.RS 4
\fB(ALPHA)\fR
Exports information about the steps for the given job\&.
.RE
.PP
\fBlist\fR
.RS 4
\fB(ALPHA)\fR
Lists all jobs in a particular project\&.
.RE
.PP
\fBshow\fR
.RS 4
\fB(ALPHA)\fR
Shows a short description of the given job\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
