.TH "GCLOUD ALPHA BIGQUERY TABLES CREATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_bigquery_tables_create \- creates a table or view with a specified name
.SH "SYNOPSIS"
.sp
gcloud alpha bigquery tables create \fITABLE\fR [\fB\-\-description\fR \fIDESCRIPTION\fR] [\fB\-\-expiration\fR \fIEXPIRATION\fR] [\fB\-\-fingerprint\-job\-id\fR] [\fB\-\-if\-exists\fR \fIIF_EXISTS\fR; default="fail"] [\fB\-\-schema\fR \fISCHEMA\fR | \fB\-\-schema\-file\fR \fISCHEMA_FILE\fR] [\fB\-\-view\fR \fIVIEW\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR A view is a collection of rows selected by a query in a flag, and manipulated as a table\&. The dataset to contain the table or view must already exist, and must not contain a table or view with the specified name\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fITABLE\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
Description of the table or view\&.
.RE
.PP
\fB\-\-expiration\fR \fIEXPIRATION\fR
.RS 4
Expiration time of the table or view being created, in seconds from now\&.
.RE
.PP
\fB\-\-if\-exists\fR \fIIF_EXISTS\fR; default="fail"
.RS 4
What to do if the table to be created already exists in the dataset\&.
.RE
.PP
\fB\-\-schema\fR \fISCHEMA\fR
.RS 4
A comma\-separated list of entries of the form name[:type], where type defaults to string if not present, specifying field names and types for the table being created\&. Possible types are string, integer, float, boolean, record, and timestamp\&.
.RE
.PP
\fB\-\-schema\-file\fR \fISCHEMA_FILE\fR
.RS 4
he name of a JSON file containing a single array object, each element of which is an object with properties name, type, and, optionally, mode, specifying a schema for the table being created\&.
.RE
.PP
\fB\-\-view\fR \fIVIEW\fR
.RS 4
Create a view with this SQL query\&. (If this flag is not specified, a table is created\&.)
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-fingerprint\-job\-id\fR
.RS 4
Whether to use a job id that is derived from a fingerprint of the job configuration\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBbigquery\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
