.TH "GCLOUD ALPHA BIGQUERY TABLES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_bigquery_tables \- a group of subcommands for working with BigQuery tables
.SH "SYNOPSIS"
.sp
gcloud alpha bigquery tables \fICOMMAND\fR [\fB\-\-fingerprint\-job\-id\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR A group of subcommands for working with BigQuery tables\&.
.SH "GROUP FLAGS"
.HP
\fB\-\-fingerprint\-job\-id\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBadd\-rows\fR
.RS 4
\fB(ALPHA)\fR
Adds records specified in a file to a specified existing table\&.
.RE
.PP
\fBcreate\fR
.RS 4
\fB(ALPHA)\fR
Creates a table or view with a specified name\&.
.RE
.PP
\fBdescribe\fR
.RS 4
\fB(ALPHA)\fR
Displays metadata about a table or view\&.
.RE
.PP
\fBlist\fR
.RS 4
\fB(ALPHA)\fR
Lists the name of each table or view in a specified dataset\&.
.RE
.PP
\fBpatch\fR
.RS 4
\fB(ALPHA)\fR
Updates one or more attributes of a table or view\&.
.RE
.PP
\fBremove\fR
.RS 4
\fB(ALPHA)\fR
Removes a specified table or view\&.
.RE
.PP
\fBshow\-rows\fR
.RS 4
\fB(ALPHA)\fR
Displays selected rows in a specified table\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBbigquery\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
