.TH "GCLOUD SQL SSL-CERTS DESCRIBE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_sql_ssl-certs_describe \- retrieves information about an SSL cert for a Cloud SQL instance
.SH "SYNOPSIS"
.sp
gcloud sql ssl\-certs describe \fICOMMON_NAME\fR [\fB\-\-instance\fR \fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Retrieves information about an SSL cert for a Cloud SQL instance\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fICOMMON_NAME\fR
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-instance\fR \fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
.RS 4
Cloud SQL instance ID\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBsql\fR component\&. See installing components if it is not installed\&.
