.TH "GCLOUD COMPUTE DISKS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_disks \- read and manipulate Google Compute Engine disks
.SH "SYNOPSIS"
.sp
gcloud compute disks \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Read and manipulate Google Compute Engine disks\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBcreate\fR
.RE
.PP
\fBdelete\fR
.RS 4
Delete Google Compute Engine persistent disks\&.
.RE
.PP
\fBdescribe\fR
.RS 4
Describe a Google Compute Engine disk\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine disks\&.
.RE
.PP
\fBmove\fR
.RS 4
Move a disk between zones\&.
.RE
.PP
\fBsnapshot\fR
.RS 4
Snapshot Google Compute Engine persistent disks\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
