.TH "GCLOUD DNS RECORD-SETS LIST" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_dns_record-sets_list \- view the list of record\-sets in a managed\-zone
.SH "SYNOPSIS"
.sp
gcloud dns record\-sets list [\fB\-\-limit\fR \fILIMIT\fR] [\fB\-\-name\fR \fINAME\fR] [\fB\-\-type\fR \fITYPE\fR] [\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
This command displays the list of record\-sets contained within the specified managed\-zone\&.
.SH "FLAGS"
.HP
\fB\-\-limit\fR \fILIMIT\fR
.RE
.PP
\fB\-\-name\fR \fINAME\fR
.RS 4
Only list record\-sets with this exact domain name\&.
.RE
.PP
\fB\-\-type\fR \fITYPE\fR
.RS 4
Only list records of this type\&. If present, the \-\-name parameter must also be present\&.
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 4
Name of the managed\-zone whose record\-sets you want to manage\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To see the list of all record\-sets in my_zone, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets \-z my_zone list
.fi
.if n \{\
.RE
.\}
.sp
To see the list of first 10 record\-sets in my_zone, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets \-z my_zone list \-\-limit=10
.fi
.if n \{\
.RE
.\}
.sp
To see the list of \fImy\&.zone\&.com\&.\fR record\-sets in my_zone, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets \-z my_zone list \-\-name="my\&.zone\&.com\&."
.fi
.if n \{\
.RE
.\}
.sp
To see the list of \fImy\&.zone\&.com\&.\fR CNAME record\-sets in my_zone, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets \-z my_zone list \-\-name="my\&.zone\&.com\&." \e
    \-\-type="CNAME"
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBdns\fR component\&. See installing components if it is not installed\&.
