.TH "GCLOUD ALPHA DATAFLOW" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_dataflow \- read and manipulate Google Dataflow resources
.SH "SYNOPSIS"
.sp
gcloud alpha dataflow \fIGROUP\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Read and manipulate Google Dataflow resources\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "GROUPS"
.sp
\fIGROUP\fR is one of the following:
.HP
\fBjobs\fR
A group of subcommands for working with Dataflow jobs\&.
.RE
.PP
\fBmetrics\fR
.RS 4
\fB(ALPHA)\fR
A group of subcommands for working with Dataflow metrics\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
