.TH "GCLOUD ALPHA TEST" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_test \- interact with Google Cloud Test Lab
.SH "SYNOPSIS"
.sp
gcloud alpha test \fIGROUP\fR | \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Explore devices and OS versions available as test targets, run tests, monitor test progress, and view detailed test results\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "GROUPS"
.sp
\fIGROUP\fR is one of the following:
.HP
\fBdevices\fR
Explore testing device environments and characteristics\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBrun\fR
.RS 4
\fB(ALPHA)\fR
Invoke a test in Google Cloud Test Lab and view test results\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
