.TH "GCLOUD ALPHA PROJECTS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_projects \- manage your Projects
.SH "SYNOPSIS"
.sp
gcloud alpha projects \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Commands to get information about your Google Developer Projects\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBadd\-iam\-policy\-binding\fR
Add IAM policy binding for a Project\&.
.RE
.PP
\fBdescribe\fR
.RS 4
\fB(ALPHA)\fR
Show metadata for a Project\&.
.RE
.PP
\fBget\-iam\-policy\fR
.RS 4
\fB(ALPHA)\fR
Get IAM policy for a Project\&.
.RE
.PP
\fBlist\fR
.RS 4
\fB(ALPHA)\fR
List all active Projects\&.
.RE
.PP
\fBremove\-iam\-policy\-binding\fR
.RS 4
\fB(ALPHA)\fR
Remove IAM policy binding for a Project\&.
.RE
.PP
\fBset\-iam\-policy\fR
.RS 4
\fB(ALPHA)\fR
Set IAM policy for a Project\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBalpha\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
