.TH "GCLOUD DNS MANAGED-ZONES CREATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_dns_managed-zones_create \- create a Cloud DNS managed\-zone
.SH "SYNOPSIS"
.sp
gcloud dns managed\-zones create \fIZONE_NAME\fR \fB\-\-description\fR \fIDESCRIPTION\fR \fB\-\-dns\-name\fR \fIDNS_NAME\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
This command creates a Cloud DNS managed\-zone\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIZONE_NAME\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
Short description for the managed\-zone\&.
.RE
.PP
\fB\-\-dns\-name\fR \fIDNS_NAME\fR
.RS 4
The DNS name suffix that will be managed with the created zone\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To create a managed\-zone, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns managed\-zones create my_zone \-\-dns_name my\&.zone\&.com\&. \e
    \-\-description "My zone!"
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBdns\fR component\&. See installing components if it is not installed\&.
