.TH "GCLOUD COMPUTE BACKEND-SERVICES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_backend-services \- list, create, and delete backend services
.SH "SYNOPSIS"
.sp
gcloud compute backend\-services \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
List, create, and delete backend services\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBadd\-backend\fR
.RE
.PP
\fBcreate\fR
.RS 4
Create a backend service\&.
.RE
.PP
\fBdelete\fR
.RS 4
Delete backend services\&.
.RE
.PP
\fBdescribe\fR
.RS 4
Describe a backend service\&.
.RE
.PP
\fBedit\fR
.RS 4
Modify backend services\&.
.RE
.PP
\fBget\-health\fR
.RS 4
Get backend health statuses from a backend service\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine backend services\&.
.RE
.PP
\fBremove\-backend\fR
.RS 4
Remove a backend from a backend service\&.
.RE
.PP
\fBupdate\fR
.RS 4
Update a backend service\&.
.RE
.PP
\fBupdate\-backend\fR
.RS 4
Update an existing backend in a backend service\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
