.TH "GCLOUD BETA CONTAINER CLUSTERS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_beta_container_clusters \- deploy and teardown Google Container Engine clusters
.SH "SYNOPSIS"
.sp
gcloud beta container clusters \fICOMMAND\fR [\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(BETA)\fR Deploy and teardown Google Container Engine clusters\&.
.SH "GROUP FLAGS"
.HP
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBcreate\fR
.RS 4
\fB(BETA)\fR
Create a cluster for running containers\&.
.RE
.PP
\fBdelete\fR
.RS 4
\fB(BETA)\fR
Delete an existing cluster for running containers\&.
.RE
.PP
\fBdescribe\fR
.RS 4
\fB(BETA)\fR
Describe an existing cluster for running containers\&.
.RE
.PP
\fBlist\fR
.RS 4
\fB(BETA)\fR
List existing clusters for running containers\&.
.RE
.PP
\fBupgrade\fR
.RS 4
\fB(BETA)\fR
Upgrade an existing cluster for running containers\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in BETA and may change without notice\&.
