.TH "GCLOUD ALPHA BIGQUERY TABLES ADD-ROWS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_bigquery_tables_add-rows \- adds records specified in a file to a specified existing table
.SH "SYNOPSIS"
.sp
gcloud alpha bigquery tables add\-rows \fITARGET_TABLE\fR [\fB\-\-file\fR \fIFILE\fR] [\fB\-\-fingerprint\-job\-id\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR The records are specified in the file as newline delimited JSON\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fITARGET_TABLE\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-file\fR \fIFILE\fR
.RS 4
The file containing the newline\-delimited JSON\&. Defaults to stdin\&.
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-fingerprint\-job\-id\fR
.RS 4
Whether to use a job id that is derived from a fingerprint of the job configuration\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBbigquery\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
