.TH "GCLOUD COMPUTE INSTANCE-TEMPLATES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_instance-templates \- read and manipulate Google Compute Engine instances templates
.SH "SYNOPSIS"
.sp
gcloud compute instance\-templates \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Read and manipulate Google Compute Engine instances templates\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBcreate\fR
.RE
.PP
\fBdelete\fR
.RS 4
Delete Google Compute Engine virtual machine instance templates\&.
.RE
.PP
\fBdescribe\fR
.RS 4
Describe a virtual machine instance template\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine instance tempates\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
