.TH "GCLOUD ALPHA DATAFLOW LOGS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_dataflow_logs \- a group of subcommands for working with Dataflow logs
.SH "SYNOPSIS"
.sp
gcloud alpha dataflow logs \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR A group of subcommands for working with Dataflow logs\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBlist\-messages\fR
Retrieve the logs from a specific job using the GetMessages RPC\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is an internal implementation detail and may change or disappear without notice\&.
.sp
This command is currently in ALPHA and may change without notice\&.
