.TH "GCLOUD ALPHA DATAFLOW JOBS SHOW" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_dataflow_jobs_show \- shows a short description of the given job
.SH "SYNOPSIS"
.sp
gcloud alpha dataflow jobs show \fIJOB_ID\fR [\fB\-\-environment\fR] [\fB\-\-steps\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Shows a short description of the given job\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIJOB_ID\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-environment\fR
.RS 4
If present, the environment will be listed\&.
.RE
.PP
\fB\-\-steps\fR
.RS 4
If present, the steps will be listed\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
