.TH "GCLOUD ALPHA BIGQUERY TABLES DESCRIBE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_bigquery_tables_describe \- displays metadata about a table or view
.SH "SYNOPSIS"
.sp
gcloud alpha bigquery tables describe \fITABLE_OR_VIEW\fR [\fB\-\-fingerprint\-job\-id\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Displays metadata about a table or view\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fITABLE_OR_VIEW\fR
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-fingerprint\-job\-id\fR
.RS 4
Whether to use a job id that is derived from a fingerprint of the job configuration\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBbigquery\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
