.TH "GCLOUD ALPHA DATAFLOW LOGS LIST-MESSAGES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_dataflow_logs_list-messages \- retrieve the logs from a specific job using the GetMessages RPC
.SH "SYNOPSIS"
.sp
gcloud alpha dataflow logs list\-messages \fIJOB_ID\fR [\fB\-\-after\fR \fIAFTER\fR] [\fB\-\-before\fR \fIBEFORE\fR] [\fB\-\-importance\fR \fIIMPORTANCE\fR; default="warning"] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR This is intended for short\-term use and will be removed once the CLI based on Cloud Logging is available\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIJOB_ID\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-after\fR \fIAFTER\fR
.RS 4
Only display messages logged after the given time\&.
.RE
.PP
\fB\-\-before\fR \fIBEFORE\fR
.RS 4
Only display messages logged before the given time\&.
.RE
.PP
\fB\-\-importance\fR \fIIMPORTANCE\fR; default="warning"
.RS 4
Minimum importance a message must have to be displayed
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is an internal implementation detail and may change or disappear without notice\&.
.sp
This command is currently in ALPHA and may change without notice\&.
