.TH "GCLOUD COMPUTE INSTANCE-TEMPLATES DELETE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_instance-templates_delete \- delete Google Compute Engine virtual machine instance templates
.SH "SYNOPSIS"
.sp
gcloud compute instance\-templates delete \fINAME\fR [\fINAME\fR \&...] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute instance\-templates delete\fR deletes one or more Google Compute Engine virtual machine instance templates\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fINAME\fR [\fINAME\fR \&...]
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
