.TH "GCLOUD BETA DEPLOYMENT-MANAGER DEPLOYMENTS CREATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_beta_deployment-manager_deployments_create \- create a deployment
.SH "SYNOPSIS"
.sp
gcloud beta deployment\-manager deployments create \fIDEPLOYMENT_NAME\fR [\fB\-\-async\fR] \fB\-\-config\fR \fICONFIG\fR [\fB\-\-description\fR \fIDESCRIPTION\fR] [\fB\-\-preview\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(BETA)\fR This command inserts (creates) a new deployment based on a provided config file\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIDEPLOYMENT_NAME\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-async\fR
.RS 4
Return immediately and print information about the Operation in progress rather than waiting for the Operation to complete\&. (default=False)
.RE
.PP
\fB\-\-config\fR \fICONFIG\fR
.RS 4
Filename of config which specifies resources to deploy\&.
.RE
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
Optional description of the deployment to insert\&.
.RE
.PP
\fB\-\-preview\fR
.RS 4
Preview the requested create without actually instantiating the underlying resources\&. (default=False)
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To create a new deployment, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager deployments create my\-deployment \e
    \-\-config config\&.yaml \-\-description "My deployment"
.fi
.if n \{\
.RE
.\}
.sp
To preview a deployment without actually creating resources, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager deployments create \e
    my\-new\-deployment \-\-config config\&.yaml \-\-preview
.fi
.if n \{\
.RE
.\}
.sp
To instantiate a deployment that has been previewed, issue an update command for that deployment without specifying a config file\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in BETA and may change without notice\&.
