.TH "GCLOUD ALPHA DATAFLOW METRICS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_dataflow_metrics \- a group of subcommands for working with Dataflow metrics
.SH "SYNOPSIS"
.sp
gcloud alpha dataflow metrics \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR A group of subcommands for working with Dataflow metrics\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBtail\fR
Retrieves the metrics from a specific job\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
