.TH "GCLOUD BETA DEPLOYMENT-MANAGER" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_beta_deployment-manager \- manage Deployments of cloud resources using version 2 beta of the API
.SH "SYNOPSIS"
.sp
gcloud beta deployment\-manager \fIGROUP\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(BETA)\fR Manage Deployments of cloud resources using version 2 beta of the API\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "GROUPS"
.sp
\fIGROUP\fR is one of the following:
.HP
\fBdeployments\fR
Commands for Deployment Manager V2 deployments\&.
.RE
.PP
\fBmanifests\fR
.RS 4
\fB(BETA)\fR
Commands for Deployment Manager V2 manifests\&.
.RE
.PP
\fBoperations\fR
.RS 4
\fB(BETA)\fR
Commands for Deployment Manager V2 operations\&.
.RE
.PP
\fBresources\fR
.RS 4
\fB(BETA)\fR
Commands for Deployment Manager V2 resources\&.
.RE
.PP
\fBtypes\fR
.RS 4
\fB(BETA)\fR
Commands for Deployment Manager V2 types\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in BETA and may change without notice\&.
