.TH "GCLOUD ALPHA GENOMICS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_genomics \- manage Genomics resources using version 1 beta 2 of the API
.SH "SYNOPSIS"
.sp
gcloud alpha genomics \fIGROUP\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Manage Genomics resources using version 1 beta 2 of the API\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "GROUPS"
.sp
\fIGROUP\fR is one of the following:
.HP
\fBdatasets\fR
Commands for Genomics datasets\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
