.TH "GCLOUD BETA DEPLOYMENT-MANAGER OPERATIONS LIST" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_beta_deployment-manager_operations_list \- list operations in a project
.SH "SYNOPSIS"
.sp
gcloud beta deployment\-manager operations list [\fB\-\-limit\fR \fILIMIT\fR] [\fB\-\-simple\-list\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(BETA)\fR Prints a table with summary information on all operations in the project\&.
.SH "FLAGS"
.HP
\fB\-\-limit\fR \fILIMIT\fR
.RE
.PP
\fB\-\-simple\-list\fR
.RS 4
If true, only the list of resource IDs is printed\&. If false, prints a human\-readable table of resource information\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To print out a list of operations with some summary information about each, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager operations list
.fi
.if n \{\
.RE
.\}
.sp
To print only the name of each operation, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager operations list \-\-simple\-list
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in BETA and may change without notice\&.
