.TH "GCLOUD DNS RECORD-SETS TRANSACTION" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_dns_record-sets_transaction \- make scriptable and transactional changes to your record\-sets
.SH "SYNOPSIS"
.sp
gcloud dns record\-sets transaction \fICOMMAND\fR [\fB\-\-transaction\-file\fR \fITRANSACTION_FILE\fR; default="transaction\&.yaml"] [\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Make scriptable and transactional changes to your record\-sets\&.
.SH "FLAGS"
.HP
\fB\-\-transaction\-file\fR \fITRANSACTION_FILE\fR; default="transaction\&.yaml"
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 4
Name of the managed\-zone whose record\-sets you want to manage\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBabort\fR
.RS 4
Abort transaction\&.
.RE
.PP
\fBadd\fR
.RS 4
Append a record\-set addition to the transaction\&.
.RE
.PP
\fBdescribe\fR
.RS 4
Describe the transaction\&.
.RE
.PP
\fBexecute\fR
.RS 4
Execute the transaction on Cloud DNS\&.
.RE
.PP
\fBremove\fR
.RS 4
Append a record\-set deletion to the transaction\&.
.RE
.PP
\fBstart\fR
.RS 4
Start a transaction\&.
.RE
.SH "EXAMPLES"
.sp
To start a transaction, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets transaction start
.fi
.if n \{\
.RE
.\}
.sp
To append a record\-set addition to the transaction, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets transaction add \-\-name RECORD_SET_NAME \e
    \-\-ttl TTL \-\-type TYPE DATA
.fi
.if n \{\
.RE
.\}
.sp
To append a record\-set removal to the transaction, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets transaction remove \-\-name RECORD_SET_NAME \e
    \-\-ttl TTL \-\-type TYPE DATA
.fi
.if n \{\
.RE
.\}
.sp
To look at the details of the transaction, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets transaction describe
.fi
.if n \{\
.RE
.\}
.sp
To delete the transaction, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets transaction abort
.fi
.if n \{\
.RE
.\}
.sp
To execute the transaction, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets transaction execute
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBdns\fR component\&. See installing components if it is not installed\&.
