.TH "GCLOUD ALPHA BIGQUERY TABLES PATCH" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_bigquery_tables_patch \- updates one or more attributes of a table or view
.SH "SYNOPSIS"
.sp
gcloud alpha bigquery tables patch \fITABLE_OR_VIEW\fR [\fB\-\-description\fR \fIDESCRIPTION\fR] [\fB\-\-expiration\fR \fIEXPIRATION\fR] [\fB\-\-fingerprint\-job\-id\fR] [\fB\-\-friendly\-name\fR \fIFRIENDLY_NAME\fR] [\fB\-\-schema\fR \fISCHEMA\fR | \fB\-\-schema\-file\fR \fISCHEMA_FILE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR The attributes that may be updated are the description, expiration time, friendly name, and schema\&. A schema may be updated only for a table, not a view\&. The new schema is specified by exactly one of the \-\-schema or \-\-schema\-file flags\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fITABLE_OR_VIEW\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 4
Description of the table or view\&.
.RE
.PP
\fB\-\-expiration\fR \fIEXPIRATION\fR
.RS 4
Expiration time, in seconds from now, of a table or view\&.
.RE
.PP
\fB\-\-friendly\-name\fR \fIFRIENDLY_NAME\fR
.RS 4
Friendly name of the table\&.
.RE
.PP
\fB\-\-schema\fR \fISCHEMA\fR
.RS 4
A comma\-separated list of entries of the form name[:type], where type defaults to string if not present, specifying field names and types in the new schema for the table\&. Possible types are string, integer, float, boolean, record, and timestamp\&.
.RE
.PP
\fB\-\-schema\-file\fR \fISCHEMA_FILE\fR
.RS 4
The name of a JSON file containing a single array object, each element of which is an object with properties name, type, and, optionally, mode, specifying a new schema for the table\&. Possible types are string, integer, float, boolean, record, and timestamp\&. Possible modes are NULLABLE, REQUIRED, and REPEATED\&.
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-fingerprint\-job\-id\fR
.RS 4
Whether to use a job id that is derived from a fingerprint of the job configuration\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBbigquery\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
