.TH "GCLOUD COMPUTE COPY-FILES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_copy-files \- copy files to and from Google Compute Engine virtual machines
.SH "SYNOPSIS"
.sp
gcloud compute copy\-files [\fIINSTANCE\fR:]\fISRC\fR [[\fIINSTANCE\fR:]\fISRC\fR \&...] [\fIINSTANCE\fR:]\fIDEST\fR [\fB\-\-dry\-run\fR] [\fB\-\-plain\fR] [\fB\-\-ssh\-key\-file\fR \fISSH_KEY_FILE\fR] [\fB\-\-zone\fR \fIZONE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute copy\-files\fR copies files between a virtual machine instance and your local machine\&.
.sp
To denote a remote file, prefix the file name with the virtual machine instance name (e\&.g\&., \fIexample\-instance\fR:/\fIFILE\fR)\&. To denote a local file, do not add a prefix to the file name (e\&.g\&., /\fIFILE\fR)\&. For example, to copy a remote directory to your local host, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute copy\-files example\-instance:~/REMOTE\-DIR \e
    ~/LOCAL\-DIR \-\-zone us\-central1\-a
.fi
.if n \{\
.RE
.\}
.sp
In the above example, \fI~/REMOTE\-DIR\fR from \fIexample\-instance\fR is copied into the ~/\fILOCAL\-DIR\fR directory\&.
.sp
Conversely, files from your local computer can be copied to a virtual machine:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute copy\-files ~/LOCAL\-FILE\-1 ~/LOCAL\-FILE\-2 \e
    example\-instance:~/REMOTE\-DIR \-\-zone us\-central1\-a
.fi
.if n \{\
.RE
.\}
.sp
If a file contains a colon (\fI:\fR), you must specify it by either using an absolute path or a path that begins with \fI\&./\fR\&.
.sp
Under the covers, \fBscp(1)\fR is used to facilitate the transfer\&.
.sp
When the destination is local, all sources must be the same virtual machine instance\&. When the destination is remote, all source must be local\&.
.SH "POSITIONAL ARGUMENTS"
.HP
[\fIINSTANCE\fR:]\fISRC\fR [[\fIINSTANCE\fR:]\fISRC\fR \&...]
.RE
.PP
[\fIINSTANCE\fR:]\fIDEST\fR
.RS 4
Specifies a destination for the source files\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-dry\-run\fR
.RS 4
If provided, prints the command that would be run to standard out instead of executing it\&.
.RE
.PP
\fB\-\-plain\fR
.RS 4
Suppresses the automatic addition of
\fBssh(1)\fR/\fBscp(1)\fR
flags\&. This flag is useful if you want to take care of authentication yourself or re\-enable strict host checking\&.
.RE
.PP
\fB\-\-ssh\-key\-file\fR \fISSH_KEY_FILE\fR
.RS 4
The path to the SSH key file\&. By default, this is
\fI~/\&.ssh/google_compute_engine\fR\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the instance to copy files to/from\&. If omitted, you will be prompted to select a zone\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
