.TH "GCLOUD DNS RECORD-SETS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_dns_record-sets \- manage the record\-sets within your managed\-zones
.SH "SYNOPSIS"
.sp
gcloud dns record\-sets \fIGROUP\fR | \fICOMMAND\fR [\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Manage the record\-sets within your managed\-zones\&.
.SH "FLAGS"
.HP
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "GROUPS"
.sp
\fIGROUP\fR is one of the following:
.PP
\fBchanges\fR
.RS 4
View details about changes to your Cloud DNS record\-sets\&.
.RE
.PP
\fBtransaction\fR
.RS 4
Make scriptable and transactional changes to your record\-sets\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBexport\fR
.RS 4
Export your record\-sets into a file\&.
.RE
.PP
\fBimport\fR
.RS 4
Import record\-sets into your managed\-zone\&.
.RE
.PP
\fBlist\fR
.RS 4
View the list of record\-sets in a managed\-zone\&.
.RE
.SH "EXAMPLES"
.sp
To import record\-sets from a BIND zone file, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets \-z MANAGED_ZONE import \e
    \-\-zone\-file\-format ZONE_FILE
.fi
.if n \{\
.RE
.\}
.sp
To export record\-sets in yaml format, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets \-z MANAGED_ZONE export
.fi
.if n \{\
.RE
.\}
.sp
To see how to make scriptable changes to your record\-sets through transactions, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets \-z MANAGED_ZONE transaction
.fi
.if n \{\
.RE
.\}
.sp
To see change details or list of all changes, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets \-z MANAGED_ZONE changes
.fi
.if n \{\
.RE
.\}
.sp
To see the list of all record\-sets, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets \-z MANAGED_ZONE list
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBdns\fR component\&. See installing components if it is not installed\&.
