.TH "GCLOUD BETA DEPLOYMENT-MANAGER DEPLOYMENTS UPDATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_beta_deployment-manager_deployments_update \- update a deployment based on a provided config file
.SH "SYNOPSIS"
.sp
gcloud beta deployment\-manager deployments update \fIDEPLOYMENT_NAME\fR [\fB\-\-async\fR] [\fB\-\-config\fR \fICONFIG\fR] [\fB\-\-create\-policy\fR \fICREATE_POLICY\fR; default="CREATE_OR_ACQUIRE"] [\fB\-\-delete\-policy\fR \fIDELETE_POLICY\fR; default="DELETE"] [\fB\-\-preview\fR] [\fB\-\-update\-policy\fR \fIUPDATE_POLICY\fR; default="PATCH"] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(BETA)\fR This command will update a deployment with the new config file provided\&. Different policies for create, update, and delete policies can be specified\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIDEPLOYMENT_NAME\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-async\fR
.RS 4
Return immediately and print information about the Operation in progress rather than waiting for the Operation to complete\&. (default=False)
.RE
.PP
\fB\-\-config\fR \fICONFIG\fR
.RS 4
Filename of config which specifies resources to deploy\&. Required unless launching an already\-previewed update to this deployment\&.
.RE
.PP
\fB\-\-create\-policy\fR \fICREATE_POLICY\fR; default="CREATE_OR_ACQUIRE"
.RS 4
Create policy for resources that have changed in the update\&. Can be CREATE_OR_ACQUIRE (default) or ACQUIRE\&.
.RE
.PP
\fB\-\-delete\-policy\fR \fIDELETE_POLICY\fR; default="DELETE"
.RS 4
Delete policy for resources that have changed in the update\&. Can be DELETE (default) or ABANDON\&.
.RE
.PP
\fB\-\-preview\fR
.RS 4
Preview the requested update without making any changes to theunderlying resources\&. (default=False)
.RE
.PP
\fB\-\-update\-policy\fR \fIUPDATE_POLICY\fR; default="PATCH"
.RS 4
Update policy for resources that have changed in the update\&. Can be PATCH (default) or UPDATE\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To update an existing deployment with a new config file, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager deployments update my\-deployment \e
    \-\-config new_config\&.yaml
.fi
.if n \{\
.RE
.\}
.sp
To preview an update to an existing deployment without actually modifying the resources, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager deployments update my\-deployment \e
    \-\-config new_config\&.yaml \-\-preview
.fi
.if n \{\
.RE
.\}
.sp
To apply an update that has been previewed, provide the name of the previewed deployment, and no config file:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager deployments update my\-deployment
.fi
.if n \{\
.RE
.\}
.sp
To specify different create, update, or delete policies, include any subset of the following flags;
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager deployments update my\-deployment \e
    \-\-config new_config\&.yaml \-\-create\-policy ACQUIRE \e
    \-\-update\-policy UPDATE \-\-delete\-policy ABANDON
.fi
.if n \{\
.RE
.\}
.sp
To perform an update without waiting for the operation to complete, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager deployments update my\-deployment \e
    \-\-config new_config\&.yaml \-\-async
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in BETA and may change without notice\&.
