.TH "GCLOUD ALPHA BIGQUERY JOBS WAIT" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_bigquery_jobs_wait \- waits up to a specified number of seconds for a specified job to finish
.SH "SYNOPSIS"
.sp
gcloud alpha bigquery jobs wait \fIJOB_ID\fR [\fB\-\-changed\-status\-only\fR] [\fB\-\-fingerprint\-job\-id\fR] [\fB\-\-ignore\-error\fR] [\fB\-\-max\-wait\fR \fIMAX_WAIT\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Waits up to a specified number of seconds for a specified job to finish\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIJOB_ID\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-changed\-status\-only\fR
.RS 4
When reporting the progress of the job being waited for, display only changes in status rather than reporting current status periodically\&.
.RE
.PP
\fB\-\-ignore\-error\fR
.RS 4
Do not exit the command with an error if the job finishes in an error state\&. (The default behavior is to exit with an error if the job finishes in an error state\&.)
.RE
.PP
\fB\-\-max\-wait\fR \fIMAX_WAIT\fR
.RS 4
The number of seconds after which execution of this command terminates even if the specified job has not finished\&. If not specified, this command waits until the specified job finishes\&.
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-fingerprint\-job\-id\fR
.RS 4
Whether to use a job id that is derived from a fingerprint of the job configuration\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBbigquery\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
