.TH "GCLOUD COMPUTE PROJECT-INFO REMOVE-METADATA" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_project-info_remove-metadata \- remove project\-wide metadata entries
.SH "SYNOPSIS"
.sp
gcloud compute project\-info remove\-metadata [\fB\-\-all\fR | \fB\-\-keys\fR \fIKEY\fR,[\fIKEY\fR,\&...]] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute project\-info remove\-metadata\fR can be used to remove project\-wide metadata entries\&.
.SH "FLAGS"
.HP
\fB\-\-all\fR
.RE
.PP
\fB\-\-keys\fR \fIKEY\fR,[\fIKEY\fR,\&...]
.RS 4
The keys of the entries to remove\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
