.TH "GCLOUD DNS PROJECT-INFO DESCRIBE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_dns_project-info_describe \- view Cloud DNS related information for a project
.SH "SYNOPSIS"
.sp
gcloud dns project\-info describe \fIPROJECT_ID\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
This command displays Cloud DNS related information for your project including quotas for various resources and operations\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIPROJECT_ID\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To display Cloud DNS related information for your project, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns project\-info describe my_project_id
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBdns\fR component\&. See installing components if it is not installed\&.
