.TH "GCLOUD COMPUTE URL-MAPS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_url-maps \- list, create, and delete URL maps
.SH "SYNOPSIS"
.sp
gcloud compute url\-maps \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
List, create, and delete URL maps\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBadd\-host\-rule\fR
.RE
.PP
\fBadd\-path\-matcher\fR
.RS 4
Add a path matcher to a URL map\&.
.RE
.PP
\fBcreate\fR
.RS 4
Create a URL map\&.
.RE
.PP
\fBdelete\fR
.RS 4
Delete URL maps\&.
.RE
.PP
\fBdescribe\fR
.RS 4
Describe a URL map\&.
.RE
.PP
\fBedit\fR
.RS 4
Modify URL maps\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine URL maps\&.
.RE
.PP
\fBremove\-host\-rule\fR
.RS 4
Remove a host rule from a URL map\&.
.RE
.PP
\fBremove\-path\-matcher\fR
.RS 4
Remove a path matcher from a URL map\&.
.RE
.PP
\fBset\-default\-service\fR
.RS 4
Change the default service of a URL map\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
