.TH "GCLOUD DNS MANAGED-ZONES DESCRIBE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_dns_managed-zones_describe \- view the details of a Cloud DNS managed\-zone
.SH "SYNOPSIS"
.sp
gcloud dns managed\-zones describe \fIZONE_NAME\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
This command displays the details of the specified managed\-zone\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIZONE_NAME\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To display the details of your managed\-zone, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns managed\-zones describe my_zone
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBdns\fR component\&. See installing components if it is not installed\&.
