.TH "GCLOUD BETA SQL CONNECT" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_beta_sql_connect \- connects to a Cloud SQL instance
.SH "SYNOPSIS"
.sp
gcloud beta sql connect \fIINSTANCE\fR [\fB\-\-user\fR \fIUSER\fR, \fB\-u\fR \fIUSER\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(BETA)\fR Connects to a Cloud SQL instance\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIINSTANCE\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-user\fR \fIUSER\fR, \fB\-u\fR \fIUSER\fR
.RS 4
Cloud SQL instance user to connect as\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in BETA and may change without notice\&.
