.TH "GCLOUD ALPHA BIGQUERY COPY" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_bigquery_copy \- copy one table to another
.SH "SYNOPSIS"
.sp
gcloud alpha bigquery copy \fISOURCE\fR \fIDESTINATION\fR [\fB\-\-async\fR] [\fB\-\-fingerprint\-job\-id\fR] [\fB\-\-if\-exists\fR \fIIF_EXISTS\fR; default="prompt"] [\fB\-\-job\-id\fR \fIJOB_ID\fR] [\fB\-\-status\fR \fISTATUS\fR; default="periodic"] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR If the table does not exist, it is created\&. Otherwise, use \-\-if\-exist flag to choose desired behaviour\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fISOURCE\fR
.RE
.PP
\fIDESTINATION\fR
.RS 4
the table to be copied to
.RE
.SH "FLAGS"
.PP
\fB\-\-async\fR
.RS 4
If True, create an asynchronous job, and use the success of job creation as the error code\&. If False, wait for command completion before returning, and use the job completion status for error codes\&.
.RE
.PP
\fB\-\-if\-exists\fR \fIIF_EXISTS\fR; default="prompt"
.RS 4
What to do if the destination table already exists\&.
.RE
.PP
\fB\-\-job\-id\fR \fIJOB_ID\fR
.RS 4
A unique job ID to use for the request\&.
.RE
.PP
\fB\-\-status\fR \fISTATUS\fR; default="periodic"
.RS 4
Whether the status of the copying job should be reported periodically, every time the status changes, or not at all\&.
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-fingerprint\-job\-id\fR
.RS 4
Whether to use a job id that is derived from a fingerprint of the job configuration\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To copy table from projectX to current project in datasetY:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud alpha bigquery copy projectX/datasetX/tableX \e
    datasetY/tableY
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBbigquery\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
