.TH "GCLOUD BETA CONTAINER OPERATIONS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_beta_container_operations \- get and list operations for Google Container Engine clusters
.SH "SYNOPSIS"
.sp
gcloud beta container operations \fICOMMAND\fR [\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(BETA)\fR Get and list operations for Google Container Engine clusters\&.
.SH "GROUP FLAGS"
.HP
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBdescribe\fR
.RS 4
\fB(BETA)\fR
Describe an operation\&.
.RE
.PP
\fBlist\fR
.RS 4
\fB(BETA)\fR
List operations for container clusters\&.
.RE
.PP
\fBwait\fR
.RS 4
\fB(BETA)\fR
Poll an operation for completion\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in BETA and may change without notice\&.
