.TH "GCLOUD ALPHA TEST DEVICES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_test_devices \- explore testing device environments and characteristics
.SH "SYNOPSIS"
.sp
gcloud alpha test devices \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Explore testing device environments and characteristics\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBdescribe\fR
Describe the characteristics of a specific test device in detail\&.
.RE
.PP
\fBlist\fR
.RS 4
\fB(ALPHA)\fR
List all device environments available for testing\&.
.RE
.SH "EXAMPLES"
.sp
To list all devices available for running tests, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud alpha test devices list
.fi
.if n \{\
.RE
.\}
.sp
To display detailed information about a specific device, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud alpha test devices describe DEVICE_ID
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
