.TH "GCLOUD SQL INSTANCES RESET-SSL-CONFIG" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_sql_instances_reset-ssl-config \- deletes all client certificates and generates a new server certificate
.SH "SYNOPSIS"
.sp
gcloud sql instances reset\-ssl\-config \fIINSTANCE\fR [\fB\-\-async\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Deletes all client certificates and generates a new server certificate\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIINSTANCE\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-async\fR
.RS 4
Do not wait for the operation to complete\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBsql\fR component\&. See installing components if it is not installed\&.
