.TH "GCLOUD DNS RECORD-SETS TRANSACTION EXECUTE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_dns_record-sets_transaction_execute \- execute the transaction on Cloud DNS
.SH "SYNOPSIS"
.sp
gcloud dns record\-sets transaction execute [\fB\-\-transaction\-file\fR \fITRANSACTION_FILE\fR; default="transaction\&.yaml"] [\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
This command executes the transaction on Cloud DNS\&. This will result in record\-sets being changed as specified in the transaction\&.
.SH "GROUP FLAGS"
.HP
\fB\-\-transaction\-file\fR \fITRANSACTION_FILE\fR; default="transaction\&.yaml"
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 4
Name of the managed\-zone whose record\-sets you want to manage\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To execute the transaction, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud dns record\-sets transaction execute \-z MANAGED_ZONE
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBdns\fR component\&. See installing components if it is not installed\&.
