.TH "GCLOUD ALPHA DATAFLOW JOBS EXPORT-STEPS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_dataflow_jobs_export-steps \- exports information about the steps for the given job
.SH "SYNOPSIS"
.sp
gcloud alpha dataflow jobs export\-steps \fIJOB_ID\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR The only currently supported format is to a GraphViz dot file\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIJOB_ID\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
