.TH "GCLOUD COMPUTE DISKS MOVE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_disks_move \- move a disk between zones
.SH "SYNOPSIS"
.sp
gcloud compute disks move \fIDISK\fR \fB\-\-destination\-zone\fR \fIDESTINATION_ZONE\fR [\fB\-\-zone\fR \fIZONE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute disks move\fR facilitates moving a Google Compute Engine disk volume from one zone to another\&. You cannot move a disk if it is attached to a running or stopped instance; use the gcloud compute instances move command instead\&.
.sp
For example, running: $ gcloud compute disks move example\-disk\-1 \-\-zone us\-central1\-b \e \-\-destination\-zone us\-central1\-f
.sp
will move the disk called example\-disk\-1, currently running in us\-central1\-b, to us\-central1\-f\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIDISK\fR
.RE
.SH "FLAGS"
.PP
\fB\-\-destination\-zone\fR \fIDESTINATION_ZONE\fR
.RS 4
The zone to move the disk to\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the disk to move\&. If not specified, you will be prompted to select a zone\&.
.sp
To avoid prompting when this flag is omitted, you can set the
\fIcompute/zone\fR
property:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config set compute/zone ZONE
.fi
.if n \{\
.RE
.\}
.sp
A list of zones can be fetched by running:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud compute zones list
.fi
.if n \{\
.RE
.\}
.sp
To unset the property, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud config unset compute/zone
.fi
.if n \{\
.RE
.\}
.sp
Alternatively, the zone can be stored in the environment variable
\fICLOUDSDK_COMPUTE_ZONE\fR\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
