.TH "GCLOUD BETA DEPLOYMENT-MANAGER DEPLOYMENTS DESCRIBE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_beta_deployment-manager_deployments_describe \- provide information about a deployment
.SH "SYNOPSIS"
.sp
gcloud beta deployment\-manager deployments describe \fIDEPLOYMENT_NAME\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(BETA)\fR This command prints out all available details about a deployment\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIDEPLOYMENT_NAME\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "EXAMPLES"
.sp
To display information about a deployment, run:
.sp
.if n \{\
.RS 4
.\}
.nf
$ gcloud beta deployment\-manager deployments describe my\-deployment
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBgcloud\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in BETA and may change without notice\&.
