.TH "GCLOUD ALPHA SOURCE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_alpha_source \- cloud git repository commands
.SH "SYNOPSIS"
.sp
gcloud alpha source \fICOMMAND\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fB(ALPHA)\fR Cloud git repository commands\&.
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.HP
\fBclone\fR
Clone project git repository in the current directory\&.
.RE
.PP
\fBlist\fR
.RS 4
\fB(ALPHA)\fR
Lists all repositories in a particular project\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBsource\fR component\&. See installing components if it is not installed\&.
.sp
This command is currently in ALPHA and may change without notice\&.
