.TH "GCLOUD COMPUTE HTTP-HEALTH-CHECKS DESCRIBE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_http-health-checks_describe \- display detailed information about an HTTP health check
.SH "SYNOPSIS"
.sp
gcloud compute http\-health\-checks describe \fINAME\fR [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute http\-health\-checks describe\fR displays all data associated with a Google Compute Engine HTTP health check in a project\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fINAME\fR
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
