.TH "GCLOUD COMPUTE URL-MAPS DELETE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_compute_url-maps_delete \- delete URL maps
.SH "SYNOPSIS"
.sp
gcloud compute url\-maps delete \fINAME\fR [\fINAME\fR \&...] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
\fBgcloud compute url\-maps delete\fR deletes one or more URL maps\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fINAME\fR [\fINAME\fR \&...]
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBcompute\fR component\&. See installing components if it is not installed\&.
