.TH "GCLOUD SQL OPERATIONS WAIT" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_sql_operations_wait \- waits for one or more operations to complete
.SH "SYNOPSIS"
.sp
gcloud sql operations wait \fIOPERATION\fR [\fIOPERATION\fR \&...] [\fB\-\-instance\fR \fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR] [\fIGLOBAL\-FLAG \&...\fR]
.SH "DESCRIPTION"
.sp
Waits for one or more operations to complete\&.
.SH "POSITIONAL ARGUMENTS"
.HP
\fIOPERATION\fR [\fIOPERATION\fR \&...]
.RE
.SH "GROUP FLAGS"
.PP
\fB\-\-instance\fR \fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
.RS 4
Cloud SQL instance ID\&.
.RE
.SH "GLOBAL FLAGS"
.sp
Run \fB$ \fR\fBgcloud\fR\fB help\fR for a description of flags available to all commands\&.
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBsql\fR component\&. See installing components if it is not installed\&.
